language: erlang
sudo: false
otp_release:
# Test on all supported releases accepted by the `require_otp_vsn` in rebar.config
   - 18.0
   - 17.4
   - 17.3
   - 17.1
   - 17.0
   - R16B03-1
#   - R16B03 this version is broken!
   - R16B02
   - R16B01
   - R16B
#  - R15B03-1 not available on travis
   - R15B03
   - R15B02
#   - R15B01 failing with timeout
#   - R15B failing with timeout

# since Travis is naughty and calls rebar get-deps behind our backs,
# we'll have to clean it up and build merl our selves.. (pre OTP 18.0)
script: 
  - "[ ! -d deps/merl ] || make -C deps/merl && make check"

notifications:
  irc: "chat.freenode.net#erlydtl"
  email: false
